import type {Metadata} from 'next'
import "@/css/base.css"
import "@/css/main.css"
// import "@/css/fonts.css"
import './globals.css'

import GeneralFooter from "@/components/GeneralFooter";
import Icon from "@/components/Icon";
import RussiaLogo from "public/img/russia.svg"

import localFont from 'next/font/local'

import 'swiper/css'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const proximaNova = localFont({
    src: [
        {
            path: '../.././public/fonts/proximanova_bold.otf',
            weight: '700',
            style: 'normal',
        },
        {
            path: '../../public/fonts/proximanova_regular.ttf',
            weight: '400',
            style: 'normal',
        },
    ],
    display: "swap",
    variable: "--font-proxima"
})

const data = {
    "logo": {
        "url": "https://escharts.com/img/logos/esc-logo-gray.svg",
        "alt": "Esports Charts"
    },
    "socialLinks": [
        {
            "title": "Twitter",
            "url": "https://escharts.com/external?page=https%3A%2F%2Ftwitter.com%2FesportsCharts",
            "icon": "twitter-fill"
        },
        // ... other social links
    ],
    "rankings": [
        {
            "title": "Top esports teams",
            "url": "https://escharts.com/teams?order=peak"
        },
        // ... other rankings
    ],
    "products": [
        {
            "title": "Products",
            "url": "https://escharts.com/products"
        },
        // ... other products
    ]
}

export default function RootLayout({children,}: { children: React.ReactNode }) {
    return (
        <html lang="en" className={`scroll-smooth ${proximaNova.variable}`} data-theme="dark"
              style={{"colorScheme": "dark"}}>
        <body className={"min-h-screen antialiased font-sans ti tabular-nums bg-body text-default"}>
        {children}
        <footer className={"sticky border-t top-full_vh border-card bg-body"}>
            <GeneralFooter data={data}/>
            <div className="border-t border-card">
                <div className={"flex items-center justify-between px-6 mx-auto max-w-screen-3xl 2sm-max:flex-col"}>
                    <div className="flex flex-col my-2 text-sm text-secondary">
                        <div className="my-1 mr-4 2sm-max:text-center 2sm-max:mb2">
                            All trademarks displayed on the site
                            <br className="lg-max:hidden"/>
                            are owned by third-parties and are used on this website for informational purposes
                            only.
                        </div>
                        <div className="flex items-center 2sm-max:flex-col">
                            <div className="my-1 mr-4">
                                © {new Date().getFullYear()}, Nikita Kalmychin.
                            </div>
                            <div className="flex items-center my-1 mr-4">
                                <RussiaLogo className="mr-2 rounded" width={24} height={16}/>
                                Developed in Russia
                            </div>
                            <div className="flex items-center my-1">
                                <Icon name={"localtime-fill"} className={"mr-2"}/>
                                GMT/UTC +3
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        </body>
        </html>
    )
}
